

# steps:
#    - name: 'python'
#      entrypoint: 'python'
#      args: ['-m', 'pip', 'install', '--upgrade', 'pip']

#    - name: 'python'
#      entrypoint: 'python'
#      args: ['-m', 'pip', 'install', 'r', 'requirements.txt', '--user']




#   #  - name: python
#   #    entrypoint: python
#   #    args: ['-m', 'pip', 'install', 'build', 'pytest', 'Flask', '--user']

#    - name: 'python'
#      entrypoint: 'python'
#      args: ['-m', 'build']

# artifacts:
#   pythonPackages:
#   - repository: 'https://southamerica-east1-python.pkg.dev/bharath-project-428310/artifact-test'
#     paths: ['dist/*']

# steps:
# - name: "gcr.io/cloud-builders/gcloud"
#   args:
#       [
#         "gcloud",
#         "functions",
#         "deploy",
#         "function-1",
#         "--entry-point=hello_http",
#         "--region=us-central1",
#         "--source=.",
#         "--trigger-http",
#         "--runtime=python312"
#       ]
# options:
#   logging: CLOUD_LOGGING_ONLY


steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - hello_world
  - --source=.
  - --trigger-http
  - --runtime=python37
  - --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY